
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolarPositionService", targetNamespace = "http://schemas.hu.fnt.nl/berichten/message", wsdlLocation = "file:/C:/Users/Mitchell/ProjectWorkspace/Java/SolarPositionCalculation/src/messageDefinition/SolarPositionService.wsdl")
public class SolarPositionService
    extends Service
{

    private final static URL SOLARPOSITIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOLARPOSITIONSERVICE_EXCEPTION;
    private final static QName SOLARPOSITIONSERVICE_QNAME = new QName("http://schemas.hu.fnt.nl/berichten/message", "SolarPositionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Mitchell/ProjectWorkspace/Java/SolarPositionCalculation/src/messageDefinition/SolarPositionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOLARPOSITIONSERVICE_WSDL_LOCATION = url;
        SOLARPOSITIONSERVICE_EXCEPTION = e;
    }

    public SolarPositionService() {
        super(__getWsdlLocation(), SOLARPOSITIONSERVICE_QNAME);
    }

    public SolarPositionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOLARPOSITIONSERVICE_QNAME, features);
    }

    public SolarPositionService(URL wsdlLocation) {
        super(wsdlLocation, SOLARPOSITIONSERVICE_QNAME);
    }

    public SolarPositionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOLARPOSITIONSERVICE_QNAME, features);
    }

    public SolarPositionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolarPositionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort() {
        return super.getPort(new QName("http://schemas.hu.fnt.nl/berichten/message", "WS-Port"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.hu.fnt.nl/berichten/message", "WS-Port"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOLARPOSITIONSERVICE_EXCEPTION!= null) {
            throw SOLARPOSITIONSERVICE_EXCEPTION;
        }
        return SOLARPOSITIONSERVICE_WSDL_LOCATION;
    }

}
